apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blobstorages.integreatly.org
spec:
  group: integreatly.org
  names:
    kind: BlobStorage
    listKind: BlobStorageList
    plural: blobstorages
    singular: blobstorage
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: BlobStorage is the Schema for the blobstorages API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          $ref: '#/definitions/github.com~1integr8ly~1cloud-resource-operator~1pkg~1apis~1integreatly~1v1alpha1~1types~0ResourceTypeSpec'
          description: BlobStorageSpec defines the desired state of BlobStorage
        status:
          $ref: '#/definitions/github.com~1integr8ly~1cloud-resource-operator~1pkg~1apis~1integreatly~1v1alpha1~1types~0ResourceTypeStatus'
          description: BlobStorageStatus defines the observed state of BlobStorage
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
